server.port=8081

basyx.backend=MongoDB

spring.mongodb.host=basyx-mongo
spring.mongodb.database=aas-env
spring.mongodb.authentication-database=admin
spring.mongodb.username=${MONGO_INITDB_ROOT_USERNAME}
spring.mongodb.password=${MONGO_INITDB_ROOT_PASSWORD}

basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
